name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt test
    - name: Build package
      run: sbt package
    - name: Nexus Repository Publisher for GitHub Actions
      uses: sonatype-nexus-community/nexus-repo-github-action@1.0.0
      with:
        serverUrl: https://oss.sonatype.org/content/repositories/snapshots
        username: oe3Hn+yY
        password: ${{ secrets.password }}
        format: maven2
        repository: maven-releases
        coordinates: groupId=com.tusharmath artifactId=zeromq version=1.0.0
        assets: extension=jar
        filename: ./target/scala-2.13/zio-zeromq_2.13-0.1.0-SNAPSHOT.jar
